[project]
name = "petalle-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "antonollo", email = "antoniogabrienunesmartins@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2>=2.9.13",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.46",
]

[project.scripts]
petalle-research = "petalle_research:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
